id: IA3052CF3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T09:44:33+00:00'
last_modified: '2022-06-08T17:16:44.289219+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15974
  title: དབུ་མའི་དོགས་གཅོད་རྟེན་འབྱུང་སྙིང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AC3C:
      image_group_id: I1KG15984
      title: ''
      total_pages: 414
      order: 1
      base_file: AC3C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
