id: IA3052CF3
legacy_id: P010753
ocr_import_info:
  bdrc_scan_id: W1KG15974
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T09:41:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:35:56.745569+00:00'
last_modified: 2022-08-27 13:36:37.538671
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15974
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15974
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མའི་དོགས་གཅོད་རྟེན་འབྱུང་སྙིང་པོ།
  author: ཕ་ར་དགེ་བཤེས་རྣམ་རྒྱལ་དབང་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9481672782049406
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG15984:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15984
      total_pages: 414
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15984.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9481672782049406
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
